mpi:
  - mpich
  - openmpi

mpi_version:
  # MPICH versions
  - 4.2.1    # [linux]
  - 4.3.0    # [osx]
  # OpenMPI versions
  - 4.1.6    # [linux]
  - 5.0.7    # [osx]

mpi_friendly_name:
  - MPICH
  - OpenMPI

mpi_website:
  - http://www.mpich.org/documentation/guides
  - https://www.open-mpi.org/doc/

mpi_dev_website:
  - https://github.com/pmodels/mpich
  - https://github.com/open-mpi/ompi

zip_keys:
  - mpi
  - mpi_version
  - mpi_friendly_name
  - mpi_website
  - mpi_dev_website

moose_hdf5:
  - hdf5 1.14.3         # [linux]
  - hdf5 1.14.4         # [osx]

moose_libexpat:
  - libexpat 2.7.0

### If you change these versions, change also conda/wasp/*, conda/seacas/*
moose_cmake:
  - cmake 3

### If you change these versions, change also conda/wasp/*, conda/seacas/*
moose_cc:
  - gcc 12.3.0 h915e2ae_13                                  # [linux]
  - clang 18.1.8 default_h576c50e_9                         # [not arm64 and osx]
  - clang 18.1.8 default_h474c9e2_9                         # [arm64]

### If you change these versions, change also conda/wasps/*, conda/seacas/*
moose_cxx:
  - gxx 12.3.0 h915e2ae_13                                  # [linux]
  - clangxx 18.1.8 default_heb2e8d1_9                       # [not arm64 and osx]
  - clangxx 18.1.8 default_h1ffe849_9                       # [arm64]

### If you change these versions, change also conda/seacas/*
moose_gfortran:
  - gfortran 12.3.0 h915e2ae_13                             # [linux]
  - gfortran 13.3.0 hcc3c99d_1                              # [not arm64 and osx]
  - gfortran 13.3.0 h3ef1dbf_1                              # [arm64]

### Cmake requires these be installed in order to "find" compilers
moose_ccompiler:
  - gcc_linux-64                                            # [linux]
  - clang_osx-64                                            # [not arm64 and osx]
  - clang_osx-arm64                                         # [arm64]

moose_cxxcompiler:
  - gxx_linux-64                                            # [linux]
  - clangxx_osx-64                                          # [not arm64 and osx]
  - clangxx_osx-arm64                                       # [arm64]

moose_libgfortran5:
  - libgfortran5 14.2.0 hf1ad2bd_2                          # [linux]
  - libgfortran5 14.2.0 h58528f3_105                        # [not arm64 and osx]
  - libgfortran5 14.2.0 h2c44a93_105                        # [arm64]

moose_gcc_impl:                                             # [linux]
  - gcc_impl_linux-64 12.3.0 h58ffeeb_13                    # [linux]

moose_gfortran_impl:                                        # [linux]
  - gfortran_impl_linux-64 12.3.0 h8f2110c_13               # [linux]

### Below are pinings created at the time of render
### based on above content. If any of the above
### content changes, modification will be needed below
moose_libstdcxx:                                            # [linux]
  - libstdcxx 14.2.0 h8f9b012_2                             # [linux]

moose_libstdcxx_devel:                                      # [linux]
  - libstdcxx-devel_linux-64 12.3.0 h6b66f73_113            # [linux]

moose_libcxx:
  - libcxx 20.1.2 ha0f52bf_0                                # [linux]
  - libcxx 20.1.2 hf95d169_0                                # [not arm64 and osx]
  - libcxx 20.1.2 ha82da77_0                                # [arm64]

moose_libzlib:
  - libzlib 1.3.1 hb9d3cd8_2                                # [linux]
  - libzlib 1.3.1 hd23fc13_2                                # [not arm64 and osx]
  - libzlib 1.3.1 h8359307_2                                # [arm64]

moose_icu:
  - icu 75.1 he02047a_0                                     # [linux]
  - icu 75.1 h120a0e1_0                                     # [not arm64 and osx]
  - icu 75.1 hfee45f7_0                                     # [arm64]

moose_cctools:                                              # [osx]
  - cctools_osx-64 1010.6 hd19c6af_6                        # [not arm64 and osx]
  - cctools_osx-arm64 1010.6 h3b4f5d3_6                     # [arm64]

moose_compiler_rt:                                          # [osx]
  - compiler-rt 18.1.8 h1020d70_1                           # [not arm64 and osx]
  - compiler-rt 18.1.8 h856b3c1_1                           # [arm64]

moose_clang_osx:                                            # [osx]
  - clangxx_osx-64 18.1.8 h7e5c614_24                       # [not arm64 and osx]
  - clang_osx-arm64 18.1.8 h07b0088_24                      # [arm64]

moose_llvm_openmp:                                          # [osx]
  - llvm-openmp 20.1.2 ha54dae1_0                           # [not arm64 and osx]
  - llvm-openmp 20.1.2 hdb05f8b_0                           # [arm64]

moose_llvm_tools:                                           # [osx]
  - llvm-tools 18.1.8 hc29ff6c_3                            # [not arm64 and osx]
  - llvm-tools 18.1.8 hc4b4ae8_3                            # [arm64]

moose_libclang:
  - libclang13 20.1.2 default_h9c6a7e4_0                    # [linux]
  - libclang-cpp18.1 18.1.8 default_h3571c67_9              # [not arm64 and osx]
  - libclang-cpp18.1 18.1.8 default_hf90f093_9              # [arm64]

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX13.3.sdk                                     # [osx]

macos_min_version:                                          # [osx]
  - 13.3                                                    # [osx]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin22.6.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 13.3                                                    # [osx]
